#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./2_xhs_get_user_latest_notes.sh [--out-dir DIR] [--sleep SECONDS] [--limit N]

Expected input:
  - DIR/accounts.json generated by ./1_xhs_get_keyword_user_ids.sh

Behavior:
  - Calls `xhs user-posts <user_id> --json`
  - Saves raw responses under DIR/raw/posts/
  - Updates DIR/accounts.json and DIR/accounts.csv in place
EOF
}

log() {
  printf '[%s] %s\n' "$(date '+%F %T')" "$*" >&2
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

merge_updates() {
  local source_json="$1"
  local updates_jsonl="$2"
  local target_json="$3"

  if [[ ! -s "$updates_jsonl" ]]; then
    cp "$source_json" "$target_json"
    return
  fi

  jq -s '
    .[0] as $source
    | (.[1] // []) as $updates
    | ($updates | map({key: .user_id, value: .}) | from_entries) as $updates_by_id
    | $source
    | map($updates_by_id[.user_id] // .)
    | sort_by(.user_name, .user_id)
  ' "$source_json" <(jq -s '.' "$updates_jsonl") > "$target_json"
}

write_accounts_csv() {
  local json_file="$1"
  local csv_file="$2"

  jq -r '
    ([
      "keywords",
      "user_name",
      "user_id",
      "red_id",
      "desc",
      "last_note_id",
      "last_note_title",
      "last_note_xsec_token",
      "last_note_cursor",
      "search_hits",
      "posts_error"
    ] | @csv),
    (.[] | [
      (.keywords // ""),
      (.user_name // ""),
      (.user_id // ""),
      (.red_id // ""),
      (.desc // ""),
      (.last_note_id // ""),
      (.last_note_title // ""),
      (.last_note_xsec_token // ""),
      (.last_note_cursor // ""),
      ((.search_hits // 0) | tostring),
      (.posts_error // "")
    ] | @csv)
  ' "$json_file" > "$csv_file"
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/output/latest}"
SLEEP_SECONDS="${SLEEP_SECONDS:-2}"
LIMIT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-dir)
      OUT_DIR="${2:?missing value for --out-dir}"
      shift 2
      ;;
    --sleep)
      SLEEP_SECONDS="${2:?missing value for --sleep}"
      shift 2
      ;;
    --limit)
      LIMIT="${2:?missing value for --limit}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_cmd xhs
require_cmd jq

ACCOUNTS_JSON="$OUT_DIR/accounts.json"
CSV_FILE="$OUT_DIR/accounts.csv"
POSTS_JSONL="$OUT_DIR/post-results.jsonl"
POSTS_LOG="$OUT_DIR/enrich.log"
SOURCE_JSON="$OUT_DIR/accounts.source.json"

if [[ ! -f "$ACCOUNTS_JSON" ]]; then
  printf 'Missing accounts.json: %s\n' "$ACCOUNTS_JSON" >&2
  exit 1
fi

mkdir -p "$OUT_DIR/raw/posts"
: > "$POSTS_JSONL"
: > "$POSTS_LOG"
cp "$ACCOUNTS_JSON" "$SOURCE_JSON"

if [[ -n "$LIMIT" ]]; then
  SOURCE_STREAM=(jq -c ".[:${LIMIT}][]" "$SOURCE_JSON")
else
  SOURCE_STREAM=(jq -c '.[]' "$SOURCE_JSON")
fi

total="$(jq 'length' "$SOURCE_JSON")"
if [[ -n "$LIMIT" ]]; then
  planned="$(jq ".[:${LIMIT}] | length" "$SOURCE_JSON")"
else
  planned="$total"
fi

log "Reading accounts from: $SOURCE_JSON"
log "Total accounts available: $total"
log "Accounts to process this run: $planned"

index=0
while IFS= read -r account; do
  [[ -z "$account" ]] && continue
  index=$((index + 1))

  user_id="$(jq -r '.user_id' <<<"$account")"
  user_name="$(jq -r '.user_name' <<<"$account")"
  raw_file="$OUT_DIR/raw/posts/${user_id}.json"
  err_file="$OUT_DIR/raw/posts/${user_id}.stderr.log"

  log "Fetching posts [$index]: $user_name ($user_id)"

  if xhs user-posts "$user_id" --json >"$raw_file" 2>"$err_file"; then
    jq -c --argjson account "$account" '
      . as $posts
      | $account + {
          last_note_id: ($posts.notes[0].note_id // ""),
          last_note_title: (($posts.notes[0].display_title // "")
            | gsub("[\r\n]+"; " ")
            | gsub("\\s+"; " ")
            | sub("^ "; "")
            | sub(" $"; "")),
          last_note_xsec_token: ($posts.notes[0].xsec_token // ""),
          last_note_cursor: ($posts.cursor // ""),
          posts_error: ""
        }
    ' "$raw_file" >> "$POSTS_JSONL"

    note_id="$(jq -r '.notes[0].note_id // ""' "$raw_file")"
    printf '[%s] ok user_id=%s note_id=%s\n' "$(date '+%F %T')" "$user_id" "$note_id" >> "$POSTS_LOG"
  else
    err_msg="$(tr '\n' ' ' < "$err_file" | sed 's/[[:space:]]\+/ /g')"
    jq -cn --argjson account "$account" --arg err "$err_msg" '
      $account + {
        last_note_id: "",
        last_note_title: "",
        last_note_xsec_token: "",
        last_note_cursor: "",
        posts_error: $err
      }
    ' >> "$POSTS_JSONL"

    printf '[%s] failed user_id=%s error=%s\n' "$(date '+%F %T')" "$user_id" "$err_msg" >> "$POSTS_LOG"
    log "Failed to fetch posts for $user_id"
  fi

  merge_updates "$SOURCE_JSON" "$POSTS_JSONL" "$ACCOUNTS_JSON"
  write_accounts_csv "$ACCOUNTS_JSON" "$CSV_FILE"
  sleep "$SLEEP_SECONDS"
done < <("${SOURCE_STREAM[@]}")

log "Done."
log "Updated accounts JSON: $ACCOUNTS_JSON"
log "Updated accounts CSV:  $CSV_FILE"
log "Raw posts dir:        $OUT_DIR/raw/posts"
